phases:
  pre_build:
    commands:
      - aws --version
      - REPO_URI=<tu_ecr_repo_uri>
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPO_URI
  build:
    commands:
      - docker build -t myapp:latest .
      - docker tag myapp:latest $REPO_URI:latest
  post_build:
    commands:
      - docker push $REPO_URI:latest
artifacts:
  files: []